# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BuildingFull(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, building=None, lat=None, lon=None):  # noqa: E501
        """BuildingFull - a model defined in OpenAPI

        :param building: The building of this BuildingFull.  # noqa: E501
        :type building: str
        :param lat: The lat of this BuildingFull.  # noqa: E501
        :type lat: float
        :param lon: The lon of this BuildingFull.  # noqa: E501
        :type lon: float
        """
        self.openapi_types = {
            'building': str,
            'lat': float,
            'lon': float
        }

        self.attribute_map = {
            'building': 'building',
            'lat': 'lat',
            'lon': 'lon'
        }

        self._building = building
        self._lat = lat
        self._lon = lon

    @classmethod
    def from_dict(cls, dikt) -> 'BuildingFull':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BuildingFull of this BuildingFull.  # noqa: E501
        :rtype: BuildingFull
        """
        return util.deserialize_model(dikt, cls)

    @property
    def building(self):
        """Gets the building of this BuildingFull.


        :return: The building of this BuildingFull.
        :rtype: str
        """
        return self._building

    @building.setter
    def building(self, building):
        """Sets the building of this BuildingFull.


        :param building: The building of this BuildingFull.
        :type building: str
        """

        self._building = building

    @property
    def lat(self):
        """Gets the lat of this BuildingFull.


        :return: The lat of this BuildingFull.
        :rtype: float
        """
        return self._lat

    @lat.setter
    def lat(self, lat):
        """Sets the lat of this BuildingFull.


        :param lat: The lat of this BuildingFull.
        :type lat: float
        """

        self._lat = lat

    @property
    def lon(self):
        """Gets the lon of this BuildingFull.

        เดี๋ยวจอมมาใส่  # noqa: E501

        :return: The lon of this BuildingFull.
        :rtype: float
        """
        return self._lon

    @lon.setter
    def lon(self, lon):
        """Sets the lon of this BuildingFull.

        เดี๋ยวจอมมาใส่  # noqa: E501

        :param lon: The lon of this BuildingFull.
        :type lon: float
        """

        self._lon = lon
