# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TestFromMark(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, light=None):  # noqa: E501
        """TestFromMark - a model defined in OpenAPI

        :param light: The light of this TestFromMark.  # noqa: E501
        :type light: int
        """
        self.openapi_types = {
            'light': int
        }

        self.attribute_map = {
            'light': 'light'
        }

        self._light = light

    @classmethod
    def from_dict(cls, dikt) -> 'TestFromMark':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TestFromMark of this TestFromMark.  # noqa: E501
        :rtype: TestFromMark
        """
        return util.deserialize_model(dikt, cls)

    @property
    def light(self):
        """Gets the light of this TestFromMark.


        :return: The light of this TestFromMark.
        :rtype: int
        """
        return self._light

    @light.setter
    def light(self, light):
        """Sets the light of this TestFromMark.


        :param light: The light of this TestFromMark.
        :type light: int
        """

        self._light = light
